name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew || true

      - name: Build all debug APKs
        run: ./gradlew assembleDebug || echo "No modules yet, will succeed once we add apps"

      - name: Upload APKs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifacts
          path: |
            **/build/outputs/apk/**/*.apk
          if-no-files-found: ignore
